name: Build PDF
on:
  # Trigger when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
    # could use a container with sq tools already installed
       image: texlive/texlive:latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Prepare source
      run: |
        mkdir -p pdf
        echo GITHUB Ref: ${{ github.ref }}
        MAJOR=`cat version.txt|cut -f2 `
        if [ "${{ github.ref }}" = "refs/heads/main" ]
        then
          PATCH=${GITHUB_RUN_NUMBER}
          SEPARATOR=.
          PREPARE_RELEASE=true
        else
          PATCH=RC${GITHUB_RUN_NUMBER}
          SEPARATOR=-
          PREPARE_RELEASE=false
        fi
        VERSION=${MAJOR}${SEPARATOR}${PATCH}
        echo "OBS_PREPARE_RELEASE=${PREPARE_RELEASE}" >> $GITHUB_ENV
        echo "OBS_VERSION=${VERSION}" >> $GITHUB_ENV
        echo "OBS_MAJOR_VERSION=${MAJOR}" >> $GITHUB_ENV
        echo "OBS_OUTPUT_FILENAME=Openbikesensor-Verein-Dokumente-${VERSION}.zip" >>$GITHUB_ENV
        echo $VERSION > pdf/VERSION
        echo $VERSION > pdf/version.txt
        echo Building Documents Version: $VERSION

    - name: Install build dependencies
      run: |
        apt-get update
        apt-get install -qq -y pandoc make zip

    - name: Build documents
      # xvfb-run required for thumbnails
      run: |
        make -j 

    - name: Package docs
      run: |
        zip --recurse-paths ${{ env.OBS_OUTPUT_FILENAME }} pdf

    - name: Upload Build Asset
      uses: actions/upload-artifact@v2
      with:
        name: obs-${{ env.OBS_VERSION }}
        path: |
          pdf/Satzung.pdf
        if-no-files-found: error


    - name: Create Release
      id: create_release
      if: ${{ env.OBS_PREPARE_RELEASE == 'true' }}
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.OBS_VERSION }}
        name: ${{ env.OBS_VERSION }}
        files: ${{ env.OBS_OUTPUT_FILENAME }}
        body: |
          ![GitHub downloads](https://img.shields.io/github/downloads-pre/openbikesensor/OpenBikeSensorFirmware/${{ env.OBS_VERSION }}/total) ![GitHub commits since release](https://img.shields.io/github/commits-since/openbikesensor/OpenBikeSensorFirmware/${{ github.sha }}?label=commits%20since%20${{ env.OBS_VERSION }})

          Version ${{ env.OBS_VERSION }} based on ${{ github.ref }} ${{ github.sha }}

          ${{ steps.changelog.outputs.changelog }}

          ## :tada: Major features and improvements

          ## :rocket: New features and improvements 

          ## :bug: Bug Fixes

          ## :ghost: Maintenance

          ## :construction_worker: Changes for developers / internal
        draft: true
        prerelease: true
